const data = [
  {
    id: "1",
    name: "SilverKey Executive Stays 61106 Bhumi World",
    description:
      "Did you know that we’ve got 2.5 Crore bookings since March 2020? And this is all thanks to the sanitisation & safety measures followed at our properties, from disinfecting surfaces with high-quality cleaning products and maintaining social distance to using protective gear and more.",
    breakfast: true,
    lunch: true,
    dinner: true,
    beds: 2,
    ac: true,
    price: 1377,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/106695/large/4d79a3e97747bfbd.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/106695/large/ad05ddf381c92bc6.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/106695/large/87905ce2ce6dfe46.jpg",
    ],
  },
  {
    id: "2",
    name: "SPOT ON 69894 Dream Night Lodging And Boarding",
    description:
      "The place is located near Mayur Bar. Some facilities provided by this place are card payment, power backup, CCTV cameras, 24X7 check-in, parking facility and reception.",
    breakfast: false,
    lunch: true,
    dinner: true,
    beds: 1,
    ac: false,
    price: 847,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/96228/large/b72bc3298c4b0ec6.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/96228/large/91ab43a752840f5c.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/96228/large/a52460722768f824.jpg",
    ],
  },
  {
    id: "3",
    name: "Capital O 9644 Hotel Mahadev Residency",
    description:
      "Did you know that we’ve got 2.5 Crore bookings since March 2020? And this is all thanks to the sanitisation & safety measures followed at our properties, from disinfecting surfaces with high-quality cleaning products and maintaining social distance to using protective gear and more.",
    breakfast: true,
    lunch: false,
    dinner: false,
    beds: 2,
    ac: true,
    price: 1954,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/15788/large/9ad6f6139748ecb1.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/15788/large/492333bfd9aae878.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/15788/large/43cdf2f372408ad9.jpg",
    ],
  },
  {
    id: "4",
    name: "SPOT ON 61441 Sangam Relax Point",
    description:
      "Spacious rooms painted in sober hues and furnished with modern wooden pieces make for a relaxing experience at this abode. They are brightly lit and offer adequate storage space too. There is an elevator on the premises for the convenience of guests.",
    breakfast: false,
    lunch: false,
    dinner: true,
    beds: 1,
    ac: true,
    price: 1014,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/82411/large/4472d87ea5b2f597.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/82411/large/2f993f217e2139c5.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/82411/large/ebc5f80d776b2215.jpg",
    ],
  },
  {
    id: "5",
    name: "SilverKey Executive Stays 40270 DSP Hotels",
    description:
      "The place is located near Mahape Police Station, Mahape, Mumbai, Maharashtra.There are some food joints near to this place where one can enjoy food which is delicious and sumptuous. One should try these food joints for a variety of food dishes that are available over here. Expand your taste buds by trying out new flavours.",
    breakfast: true,
    lunch: true,
    dinner: true,
    beds: 3,
    ac: false,
    price: 1399,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/104253/large/107e9a3befbea44e.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/104253/large/af7aaecf697d67f2.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/104253/large/a5a7211ff2c483f7.jpg",
    ],
  },
  {
    id: "6",
    name: "OYO 72938 Hotel Shree Krishna Residency",
    description:
      "Private Entrance, Free Wifi, 24/7 Checkin, Complimentary Breakfast, Toiletries, Attached Bathroom, Pre Book Meals, CCTV Cameras, Reception, Daily Housekeeping, Fire-Extinguisher are some of the amenities available at this property for a comfortable stay.",
    breakfast: false,
    lunch: false,
    dinner: false,
    beds: 1,
    ac: true,
    price: 1537,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/102255/large/96716a9852f59180.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/102255/large/1b3f113ff0fb8912.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/102255/large/45236af9cbc52e30.jpg",
    ],
  },
  {
    id: "7",
    name: "Collection O Mojatel AECS Layout",
    description:
      "The famous Brookfields Mall is located 0.5 km from this hotel. This property is located 5 km from KR Puram Railway Station. The rooms in the hotel come with AC, TV, Attached Bathroom, ensuring comfortable stay. The property also offers Parking Facility, Gym, 24/7 Checkin, for all its guests. Breakfast is available at this property. Collection O Mojatel AECS Layout has been wecoming guests since Mar, 2021.",
    breakfast: false,
    lunch: false,
    dinner: true,
    beds: 2,
    ac: true,
    price: 1216,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/111433/large/a5577954e031f725.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/111433/large/8bbb3d26f3842674.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/111433/large/3ffc877249624f5a.jpg",
    ],
  },
  {
    id: "8",
    name: "Capital O 28398 Mysore Gate",
    description:
      "Did you know that we’ve got 2.5 Crore bookings since March 2020? And this is all thanks to the sanitisation & safety measures followed at our properties, from disinfecting surfaces with high-quality cleaning products and maintaining social distance to using protective gear and more.",
    breakfast: true,
    lunch: true,
    dinner: true,
    beds: 2,
    ac: true,
    price: 2002,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/49398/large/a9ddeddb908c94fd.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/49398/large/16b939bd808fb363.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/49398/large/daf345276582cb13.jpg",
    ],
  },
  {
    id: "9",
    name: "SPOT ON 80376 Santa Maria",
    description:
      "The famous Infinitea is located 2 km from this hotel. This property is located 4 km from KR Puram Railway Station. The property also offers CCTV Cameras, Laundry, Fire Extinguisher, for all its guests. SPOT ON 80376 Santa Maria has been wecoming guests since Apr, 2021.",
    breakfast: true,
    lunch: false,
    dinner: true,
    beds: 3,
    ac: true,
    price: 1082,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/112008/large/c6278731cb3a2c35.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/112008/large/161afcc31a7dbc71.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/112008/large/788265a7accc1692.jpg",
    ],
  },
  {
    id: "10",
    name: "Collection O Supralisa",
    description:
      "The famous Cubbon Park is located 3 km from this hotel. This property is located 3 km from Bangalore Cantonment Railway Station. Pearl Inn, Infinitea, are some of the famous landmarks within 3 km of the hotel. The rooms in the hotel come with TV, ensuring comfortable stay. The property also offers Free Wifi, for all its guests. Collection O Supralisa has been wecoming guests since Apr, 2021.",
    breakfast: false,
    lunch: false,
    dinner: false,
    beds: 1,
    ac: true,
    price: 2139,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/111925/large/466e9f8ac58ccbd8.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/111925/large/9d164a566b68b7af.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/111925/large/6aa431666b7dbfd9.jpg",
    ],
  },
  {
    id: "11",
    name: "SPOT ON 72325 Red Cherry Wagtail",
    description:
      "Did you know that we’ve got 2.5 Crore bookings since March 2020? And this is all thanks to the sanitisation & safety measures followed at our properties, from disinfecting surfaces with high-quality cleaning products and maintaining social distance to using protective gear and more.",
    breakfast: true,
    lunch: false,
    dinner: false,
    beds: 2,
    ac: false,
    price: 952,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/101042/large/2ee0230f3616d68a.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/101042/large/93384b08c904d653.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/101042/large/47b2b735acf5d058.jpg",
    ],
  },
  {
    id: "12",
    name: "Capital O 67657 GN Suites",
    description:
      "Capital O Schmear Suites is situated near Banaswadi, Bangalore. The atmosphere is warm and comforting. The rooms are mindfully curated with exclusive interiors. Room Ventilation, Complimentary Breakfast, Laundry, 24x7 Accessible Kitchen, Wooden Floors, AC, Geyser, 24/7 Checkin, Jacuzzi, Elevator, Room Service, Free Wifi, Cutlery/Crockery, Complimentary Veg Breakfast, Modern Wardrobe, TV, Hair Dryer, Dining Area, Complimentary Buffet Breakfast, Wifi Dongle, Reception, Daily Housekeeping, Fire-Extinguisher, Bath Tub, Card Payment, Power backup, Fan, Mirror, CCTV Cameras, Attached Bathroom are some of the amenities available at this property.",
    breakfast: false,
    lunch: true,
    dinner: true,
    beds: 3,
    ac: true,
    price: 1772,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/92243/large/50a05a9927e86fb2.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/92243/large/647da94b7d4d9eb9.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/92243/large/7af5cc8665097efd.jpg",
    ],
  },
  {
    id: "13",
    name: "Capital O 62363 N R Residency",
    description:
      "Did you know that we’ve got 2.5 Crore bookings since March 2020? And this is all thanks to the sanitisation & safety measures followed at our properties, from disinfecting surfaces with high-quality cleaning products and maintaining social distance to using protective gear and more.",
    breakfast: true,
    lunch: true,
    dinner: false,
    beds: 1,
    ac: false,
    price: 1708,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/83909/large/8efeeec5a47ace35.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/83909/large/385d5902d68ae464.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/83909/large/78e04eb52eadd1fc.jpg",
    ],
  },
  {
    id: "14",
    name: "Capital O 312 Hotel Aster Inn",
    description:
      "Hotel Aster Inn is a beautiful, homely hotel located in Karol Bagh, New Delhi. It is just a 2 minute walk from the main road and close to Hanuman Chowk Bus Stop, Faiz Road Bus Stop and Jhandewalan Metro Station. The hotel has a cosy in-house restaurant and an elevator. The rooms are bright and feature lighthued trendy wooden furniture and accents. The bathrooms are aesthetic too.",
    breakfast: false,
    lunch: true,
    dinner: true,
    beds: 2,
    ac: true,
    price: 2705,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/45/large/a2a8cde095b4b05b.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/45/large/cc47dac2cb3e9a21.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/45/large/ab1d4f4343752af6.jpg",
    ],
  },
  {
    id: "15",
    name: "Capital O 325 Hotel Silver Star",
    description:
      "Hotel Prakash Habitat is a sophisticated and elegant property located in Sector 39, Gurugram. The nearest metro station is Huda City Centre metro station. The rooms are spacious and well lit. The decor is characteristic and unique at the same time. The little details on the walls of the room enhance the overall vibe of the room.",
    breakfast: false,
    lunch: false,
    dinner: false,
    beds: 3,
    ac: true,
    price: 1847,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/74/large/63f35c9bcafeb9a6.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/74/large/b80fd6996534c348.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/74/large/7b1e245f656a6b4e.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/74/large/d146d2b2c180b3d9.jpg",
    ],
  },
  {
    id: "16",
    name: "CAPITAL O11243 Vedanta",
    description:
      " Located behind the famous Medanta Hospital in Gurgaon, OYO Rooms Medicity is recommended for those who are looking for a pleasant stay experience within their budget. Well-connected to the IGI Airport (18 km), Huda City Metro Station (5.2 Km) and Gurgaon Railway Station (7 km), this property makes an ideal abode for those travelling on business. Close proximity to shopping centres is an added bonus with OYO Rooms. Attitude Alive Bar (9 Km), Soi 7 Club (10.8 Km) and Beer Factory Bar (8.5 km) are some of the best places to experience Gurgaon's happening nightlife. Those who want to keep away from the hustle-bustle of daily life, can head to the Four Fountains Spa (9 Km) for rejuvenation.",
    breakfast: true,
    lunch: false,
    dinner: false,
    beds: 1,
    ac: true,
    price: 1246,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/339/large/20d2c2cc2ce835fb.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/339/large/ee85be4e547fc783.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/339/large/5714c6b5841becfe.jpg",
    ],
  },
  {
    id: "17",
    name: "OYO 526 Hotel Asees Inn",
    description:
      "Hotel Asees Inn is a property situated near Kirti Nagar, Delhi. It is located near many key attractions of New Delhi such as Laxmi Narayan Temple, ISKCON Temple, and Talkatora Garden. The hotel is close to the Kirti Nagar railway station, Moti Nagar Metro station, F Block Kirti Nagar Bus stop and T1 Domestic Airport Terminal.",
    breakfast: false,
    lunch: false,
    dinner: false,
    beds: 3,
    ac: true,
    price: 2313,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/391/large/d28240d442d711c9.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/391/large/55341717b31b4c29.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/391/large/c018bf84ef774948.jpg",
    ],
  },
  {
    id: "18",
    name: "OYO 546 Hotel Paras International",
    description:
      "f you are looking for a comfortable and a luxury stay within your pocket, OYO Rooms 136 Karol Bagh 5/25 is your destination. The hotel is about 14.1 Km from Indira Gandhi Airport and 3.8 Km from New Delhi Railway Station. While Karol Bagh Metro Station is just 500 m away from the hotel. During your stay here, places to explore include the India Gate (6.8 Km), Laxmi Narayan Temple (1.3 Km) and Jantar Mantar (4.4 Km) along with shopping destinations like Karol Bagh Market (900 m), Gaffar Market (500 m) and Connaught Place (3.9 Km). Eating joints like Suruchi (130 m). In case of any medical emergency, you could head to BLK Super Speciality (950 m) and Sri Ganga Ram Komlet (500 m).",
    breakfast: true,
    lunch: true,
    dinner: true,
    beds: 1,
    ac: true,
    price: 1873,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/421/large/be1d4a3e99c4b158.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/421/large/81fc701b834092a6.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/421/large/af4ae25e3e6017cf.jpg",
    ],
  },
  {
    id: "19",
    name: "OYO 1824 Hotel Grand Peepal",
    description:
      "Hotel Grand Peepal is a modern property with bright and cosy interiors, and located in Balmiki Colony in Karol Bagh, Delhi. It is very close to Regharpura Bus Stop, Karol Bagh Metro Station and Delhi Sarai Rohilla Railway Station. The Karol Bagh Market, Jhandewalan Mata Mandir, Rock Garden and Talkatora Indoor Stadium are close to the property too.",
    breakfast: false,
    lunch: false,
    dinner: true,
    beds: 3,
    ac: true,
    price: 1733,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/2333/large/4ad8129a6ab28b47.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/2333/large/cfa26a59d2a9731c.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/2333/large/2b0939771c9cd7e2.jpg",
    ],
  },
  {
    id: "20",
    name: "OYO 1987 Paharganj",
    description:
      "OYO 1987 Paharganj is a standard modern hotel situated on the DB Gupta Road in Ratan Lal Market in Paharganj. Qadam Sharif, Chandini Chowk, Gurudwara Bangla Sahib, and Jantar Mantar are some popular landmarks near the hotel.",
    breakfast: true,
    lunch: true,
    dinner: true,
    beds: 2,
    ac: true,
    price: 1692,
    images: [
      "https://images.oyoroomscdn.com/uploads/hotel_image/2600/large/e30977afb9474b09.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/2600/large/4335405df60ecd57.jpg",
      "https://images.oyoroomscdn.com/uploads/hotel_image/2600/large/776a0c043a604e8f.jpg",
    ],
  },
];

export default data;
